{
 "title": "Player",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "player" }
  ]
 },
 "panels": [
  {
   "title": "Blocks broken",
   "type": "xychart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{compose_service=\"vsserver\"} |= `DidBreakBlock` |= `${player}`",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Movements",
   "type": "xychart",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "{compose_service=\"vsserver\"} |= `PlayerCoords` |= `${player}`"
    }
   ]
  },
  {
   "title": "Blocks placement",
   "type": "xychart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{compose_service=\"vsserver\"} |= `DidPlaceBlock` |= `${player}`"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "{compose_service=\"vsserver\"} |= `${player}` |= ``",
     "maxLines": 5000
    }
   ]
  },
  {
   "title": "Death",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({compose_service=\"vsserver\"} |= `Death` |= `${player}` [$__auto])"
    }
   ]
  },
  {
   "title": "Blocks placement",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({compose_service=\"vsserver\"} |= `DidPlaceBlock` |= `${player}` [$__auto])"
    }
   ]
  },
  {
   "title": "Blocks broken",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count_over_time({compose_service=\"vsserver\"} |= `DidBreakBlock` |= `${player}` [$__auto])"
    }
   ]
  }
 ]
}